In [ ]:
!pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Downloading scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 64.5 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed scikit-learn-1.7.2

In [ ]:
import xgboost as xgb
import shap
import pandas as pd
import numpy as np
from typing import Union, Dict, Optional, Tuple, Set, List
from math import factorial
import time
from copy import copy
from tqdm import tqdm
from collections import defaultdict
import math

from sklearn.metrics import accuracy_score, f1_score, root_mean_squared_error
from sklearn.datasets import load_diabetes, load_breast_cancer, fetch_california_housing
from sklearn.model_selection import train_test_split
import sklearn

import warnings
warnings.filterwarnings("ignore", category=FutureWarning, module=r"sklearn\..*")

In [ ]:
# Useful if you run this on google colab and downloaded the data into your drive.
# If you run the notebook in other environment remove these lines and change the 'pd.read_csv()' function in this notebook to read from
# where you saved you data
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# import woodelf from Python file in the drive
!cp /content/drive/MyDrive/...../woodelf.py /content/

import woodelf

# PDP Code

In [ ]:
class CPDVMetric(woodelf.CubeMetric):
    def calc_metric(self, s_plus: Set, s_minus: Set) -> Dict[str, float]:
        if len(s_plus & s_minus) > 0:
            return {}
        pdp_values = {}
        if len(s_plus) == 1:
            for f in s_plus:
                pdp_values[f] = 1
        if len(s_plus) == 0:
            for f in s_minus:
                pdp_values[f] = -1
        return pdp_values

In [ ]:
class PathToValuesMatrixLimitSPlus(woodelf.PathToValuesMatrix):
    # Ignored all cubes with |S^+| > MAX_S_PLUS_SIZE to reduce the complexity element of TL3**D to TL2**D*(D**MAX_S_PLUS_SIZE)
    MAX_S_PLUS_SIZE = NotImplemented

    @classmethod
    def map_patterns_to_cube(cls, features_in_path: List[str]):
        updated_wdnf_table = {0: {0: (set(), set())}}
        current_wdnf_table = None
        for feature in features_in_path:
            current_wdnf_table = updated_wdnf_table
            updated_wdnf_table = {}
            for consumer_pattern in current_wdnf_table:
                updated_wdnf_table[consumer_pattern * 2 + 0] = {}
                updated_wdnf_table[consumer_pattern * 2 + 1] = {}
                for background_pattern in current_wdnf_table[consumer_pattern]:
                    s_plus, s_minus = current_wdnf_table[consumer_pattern][background_pattern]

                    # The implementation is identical to the PathToValuesMatrix.map_patterns_to_cube implementation, except for this if.
                    if len(s_plus | {feature}) <= cls.MAX_S_PLUS_SIZE:
                        updated_wdnf_table[consumer_pattern * 2 + 1][background_pattern * 2 + 0] = (s_plus | {feature}, s_minus) # Rule 1

                    updated_wdnf_table[consumer_pattern * 2 + 0][background_pattern * 2 + 1] = (s_plus, s_minus | {feature}) # Rule 2
                    updated_wdnf_table[consumer_pattern * 2 + 1][background_pattern * 2 + 1] = (s_plus, s_minus) # Rule 3

        return updated_wdnf_table

class PathToValuesMatrixLimitSPlusTo1(PathToValuesMatrixLimitSPlus):
    # We uses the fact CPDVMetric ignored all cubes with |S^+| > 1 to reduce the complexity element of TL3**D to TL2**D*D
    MAX_S_PLUS_SIZE = 1

class PathToValuesMatrixLimitSPlusTo2(PathToValuesMatrixLimitSPlus):
    # We uses the fact PDIVOrder1Or2 ignored all cubes with |S^+| > 2 to reduce the complexity element of TL3**D to TL(2**D)*(D**2)
    MAX_S_PLUS_SIZE = 2

In [ ]:
def build_sampled_points_df(data: pd.DataFrame, k: int, seed: int = None):
    """
    Sample k points from every column.
    """
    sample_points_data = {}
    for f in data.columns:
        sample_points_data[f] = list(data[f].sample(k, random_state=seed))
        sample_points_data[f].sort()
    return pd.DataFrame(sample_points_data)[data.columns]

def build_equally_distanced_points_df(data: pd.DataFrame, k: int, percentiles: Tuple[float]):
    """
    Take equally distanced points from each column. The min point will be in the precentile percentiles[0]
    and the max point will be in the precentile percentiles[1].
    This is also the default implementation of sklearn
    """
    sample_points_data = {}
    for f in data.columns:
        low, high = np.percentile(data[f].dropna(), [percentiles[0] * 100, percentiles[1]*100])
        # get k equally spaced points between them
        points = np.linspace(low, high, k)
        sample_points_data[f] = list(points)
        sample_points_data[f].sort()
    return pd.DataFrame(sample_points_data)[data.columns]

def build_points_for_full_pdp(data: pd.DataFrame, model, as_df: bool=True):
    """
    Provide the points that will create a full PDP - a graph the will provide the PDV for every x value.
    Does this by collecting all the threshold values from the model. See Sect. of the paper.
    """
    # load the model
    model_objs = woodelf.load_decision_tree_ensamble_model(model, list(data.columns))

    # collect all the theshold values for each feature
    th_values = {f: [] for f in list(data.columns)}
    for tree in model_objs:
        for node in tree.bfs(including_myself=True, including_leaves=False):
            th_values[node.feature_name].append(node.value)

    # Make sure the thesholds are unique and sort them
    for f in th_values:
        th_values[f] = sorted(list(set(th_values[f])))

    if not as_df:
        return th_values

    # zfill
    max_th_length = max([len(thersholds) for thersholds in th_values.values()])
    for f in th_values:
        th_values[f].extend([0] * (max_th_length - len(th_values[f])) )

    # from the built thershold build the points Data Frame
    return pd.DataFrame(th_values)

In [ ]:
def build_points_for_pdp(model, data: pd.DataFrame, k: int = 100, percentiles: Tuple[float] = (0.05, 0.95), sampled: bool = False, seed: int = 42, full_pdp: bool = False, verbose : bool = True):
    start_time = time.time()
    if sampled:
        points_df = build_sampled_points_df(data, k, seed)
    elif full_pdp:
        points_df = build_points_for_full_pdp(data, model)
    else:
        points_df = build_equally_distanced_points_df(data, k, percentiles)
    if verbose:
        print(f"Building the points took: {time.time() - start_time} sec")
    return points_df

def woodelf_pdp(model, data: pd.DataFrame, k: int = 100, accurate: bool = True, centered: bool = True, GPU: bool = False,
                percentiles: Tuple[float] = (0.05, 0.95), sampled: bool = False, seed: int = 42, full_pdp: bool = False):
    """
    Compute all the PDVs needed in order to plot the PDP values of all the features. Use WOODELF!
    """
    points_df = build_points_for_pdp(model, data, k, percentiles, sampled, seed, full_pdp, verbose=True)
    return woodelf_pdp_given_points_df(model, data, points_df, accurate, centered, GPU), points_df

def woodelf_pdp_given_points_df(model, data: pd.DataFrame, sampled_points_df: pd.DataFrame, accurate: bool = True, centered: bool = True, GPU: bool = False):
    """
    Compute all the PDVs of the provided points. Use WOODELF!
    """
    metric=CPDVMetric()
    p2v = PathToValuesMatrixLimitSPlusTo1(metric)
    if accurate:
        pdvs = woodelf.calculate_background_metric(model, consumer_data=sampled_points_df, background_data=data, metric=metric, global_importance=False, GPU=GPU, path_to_matrixes_calculator=p2v)
    else:
        pdvs = woodelf.calculate_path_dependent_metric(model, consumer_data=sampled_points_df, metric=metric, global_importance=False, GPU=GPU, path_to_matrixes_calculator=p2v)
    if centered:
        return pdvs

    avg_prediction = float(model.predict(data).mean())
    for f in pdvs:
        pdvs[f] += avg_prediction
    return pdvs

## Joint DPD code

In [ ]:
# PDP joint

from itertools import combinations

def all_subsets_of_size_0_1_2(s):
    subsets = [set()]
    for k in [1,2]:
        for subset in combinations(s, k):
            subsets.append(set(subset))
    return subsets

class PDIVOrder1Or2(woodelf.CubeMetric):
    INTERACTION_VALUE = True

    def calc_metric(self, s_plus: Set, s_minus: Set) -> Dict[str, float]:
        if len(s_plus & s_minus) > 0:
            return {}

        pdivs = {}
        for sm in all_subsets_of_size_0_1_2(s_minus):
            s = tuple(s_plus | sm)
            if len(s) in [1,2]:
                pdivs[s] = (-1) ** (len(sm))
        return pdivs

def bits(n, D):
    bs = []
    for i in range(D):
        bs.append(n % 2)
        n = n // 2
    return reversed(bs)

def build_points_for_joint_pdp(points_df: pd.DataFrame):
    D = math.ceil(math.log2(len(points_df.columns)))
    data = {f: [] for f in points_df.columns}
    k = len(points_df)
    for i, f in enumerate(points_df.columns):
        for b in bits(i, D):
            if b == 0:
                data[f].extend(np.tile(points_df[f].values, k))
            elif b == 1:
                data[f].extend(np.repeat(points_df[f].values, k))
    return pd.DataFrame(data)

def first_different_bit(n1, n2, D):
    assert n1 != n2
    i = 0
    for b1, b2 in zip(bits(n1, D), bits(n2, D)):
        if b1 != b2:
            return i
        i += 1

def clip_result(pdvs, features, k):
    D = math.ceil(math.log2(len(features)))
    feature_to_index = {f:i for i,f in enumerate(features)}
    clipped = {}
    for f1, f2 in pdvs:
        i1 = feature_to_index[f1]
        i2 = feature_to_index[f2]
        h = first_different_bit(i1, i2, D)
        clipped[(f1, f2)] = pdvs[(f1, f2)][h*(k**2): (h+1)*(k**2)]
    return clipped


def woodelf_pdp_joint(model, data: pd.DataFrame, k: int = 100, accurate: bool = True, centered: bool = True, GPU: bool = False,
                percentiles: Tuple[float] = (0.05, 0.95), sampled: bool = False, seed: int = 42, full_pdp: bool = False, verbose: bool = True):
    """
    Compute all the PDVs needed in order to plot the PDP values of all the features. Use WOODELF!
    """
    start_time = time.time()
    original_points_df = build_points_for_pdp(model, data, k, percentiles, sampled, seed, full_pdp, verbose=False)
    if full_pdp:
        k = len(original_points_df)

    points_df = build_points_for_joint_pdp(original_points_df)
    if verbose:
        print(f"Building the points took: {time.time() - start_time} sec. The size of the created df {len(points_df)}")

    metric = PDIVOrder1Or2()
    p2v = PathToValuesMatrixLimitSPlusTo2(metric)
    if accurate:
        pdivs = woodelf.calculate_background_metric(
            model, consumer_data=points_df, background_data=data, metric=metric, global_importance=False, GPU=GPU, path_to_matrixes_calculator=p2v
        )
    else:
        pdivs = woodelf.calculate_path_dependent_metric(
            model, consumer_data=points_df, metric=metric, global_importance=False, GPU=GPU, path_to_matrixes_calculator=p2v
        )
    avg_prediction = float(model.predict(data).mean())
    base_pdv = np.array([avg_prediction] * len(points_df))
    zero_array = np.array([0] * len(points_df))
    pdvs = {}

    D = math.ceil(math.log2(len(points_df.columns)))
    points_parts = {f: [points_df[f].values[i:i + k**2] for i in range(0, len(points_df[f]), k**2)] for f in data.columns}
    f1_points = {}
    f2_points = {}
    for i, f1 in enumerate(data.columns):
        for j, f2 in enumerate(data.columns):
            if f1 != f2:
                pair = (f1, f2)
                pdvs[(f1,f2)] = base_pdv + pdivs.get((f1,), zero_array) + pdivs.get((f2,), zero_array) + pdivs.get(pair, zero_array)
                points_part_index = first_different_bit(i,j,D)
                f1_points[(f1,f2)] = points_parts[f1][points_part_index]
                f2_points[(f1,f2)] = points_parts[f2][points_part_index]
    clipped_pdvs = clip_result(pdvs, list(data.columns), k)
    return clipped_pdvs, f1_points, f2_points

## Any Order PDIV code

In [ ]:
from itertools import combinations

def all_subsets(s):
    subsets = []
    for k in range(len(s) + 1):
        for subset in combinations(s, k):
            subsets.append(set(subset))
    return subsets

class PDIV(woodelf.CubeMetric):
    INTERACTION_VALUE = True
    def calc_metric(
        self, s_plus: Set, s_minus: Set
    ) -> Dict[str, float]:
        if len(s_plus & s_minus) > 0:
            return {}

        pdivs = {}
        for sm in all_subsets(s_minus):
            s = tuple(s_plus | sm)
            pdivs[s] = (-1) ** (len(sm))
        return pdivs

# Datasets and Models

In [ ]:
from sklearn.datasets import load_diabetes, load_breast_cancer, fetch_california_housing

diabetes = load_diabetes(as_frame=True)
cancer = load_breast_cancer(as_frame=True)
california = fetch_california_housing(as_frame=True)

print("diabetes: ")
print(diabetes.DESCR)
print("cancer: ")
print(cancer.DESCR)
print("california_housing: ")
print(california.DESCR)


df_diabetes = diabetes.frame
df_cancer = cancer.frame
df_california = california.frame

df_diabetes.shape, df_cancer.shape, df_california.shape

diabetes:
.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

cancer:
.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - class:
            - WDBC-Malignant
            - WDBC-Benign

:Summary Statistics:

===================================== ====== ======
                                        Min    Max
===================================== ====== ======
radius (mean):                        6.981  28.11
texture (mean):                       9.71   39.28
perimeter (mean):                     43.79  188.5
area (mean):                          143.5  2501.0
smoothness (mean):                    0.053  0.163
compactness (mean):                   0.019  0.345
concavity (mean):                     0.0    0.427
concave points (mean):                0.0    0.201
symmetry (mean):                      0.106  0.304
fractal dimension (mean):             0.05   0.097
radius (standard error):              0.112  2.873
texture (standard error):             0.36   4.885
perimeter (standard error):           0.757  21.98
area (standard error):                6.802  542.2
smoothness (standard error):          0.002  0.031
compactness (standard error):         0.002  0.135
concavity (standard error):           0.0    0.396
concave points (standard error):      0.0    0.053
symmetry (standard error):            0.008  0.079
fractal dimension (standard error):   0.001  0.03
radius (worst):                       7.93   36.04
texture (worst):                      12.02  49.54
perimeter (worst):                    50.41  251.2
area (worst):                         185.2  4254.0
smoothness (worst):                   0.071  0.223
compactness (worst):                  0.027  1.058
concavity (worst):                    0.0    1.252
concave points (worst):               0.0    0.291
symmetry (worst):                     0.156  0.664
fractal dimension (worst):            0.055  0.208
===================================== ====== ======

:Missing Attribute Values: None

:Class Distribution: 212 - Malignant, 357 - Benign

:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

:Donor: Nick Street

:Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. dropdown:: References

  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
    San Jose, CA, 1993.
  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
    prognosis via linear programming. Operations Research, 43(4), pages 570-577,
    July-August 1995.
  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
    163-171.

california_housing:
.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

((442, 11), (569, 31), (20640, 9))

In [ ]:
def train_models(dfs, targets, datasets_names, train_ratio=0.8):
    models = {}
    train_sets = {}
    test_sets = {}
    for df, target, name in zip(dfs, targets, datasets_names):
        print()
        X_train, X_test, y_train, y_test = train_test_split(df[[c for c in df.columns if c != target]], df[target], train_size=train_ratio, random_state=42)
        print(f"{name}: Train set size is {len(X_train)}, test set size is {len(X_test)}, the target is {target}, number of columns is {len(X_train.columns)}")
        gradient_boosting_model = sklearn.ensemble.HistGradientBoostingRegressor(
            max_iter=100, # TODO use 100,
            max_depth=6,
            max_leaf_nodes=None,
            random_state=42
        )
        gradient_boosting_model.fit(X_train, y_train)
        y_pred = gradient_boosting_model.predict(X_test)
        if y_test.nunique() == 2:
            print(f"Accuracy: {accuracy_score(y_test, y_pred.round())}, F1 score: {f1_score(y_test, y_pred.round())}")
        else:
            print(f"RMSE: {root_mean_squared_error(y_test, y_pred)}, RMSE of always taking the mean: {root_mean_squared_error(y_test, pd.Series(y_test.mean(), index=y_test.index))}")

        models[name] = gradient_boosting_model
        train_sets[name] = X_train
        test_sets[name] = X_test

    return models, train_sets, test_sets

In [ ]:
models, trains, tests = train_models([df_diabetes, df_cancer, df_california], ["target", "target", "MedHouseVal"], ["diabetes", "cancer", "california_housing"])

diabetes: Train set size is 353, test set size is 89, the target is target, number of columns is 10
RMSE: 57.04726073307006, RMSE of always taking the mean: 72.78840394263774

cancer: Train set size is 455, test set size is 114, the target is target, number of columns is 30
Accuracy: 0.956140350877193, F1 score: 0.965034965034965

california_housing: Train set size is 16512, test set size is 4128, the target is MedHouseVal, number of columns is 8
RMSE: 0.47841679117287006, RMSE of always taking the mean: 1.1447309632576992

# Running time comparision

In [ ]:
def df_to_latex(df: pd.DataFrame):
    latex = "\\begin{tabularx}{\\columnwidth}{" + "|".join(['r'] * len(df.columns)) + "} \n"
    latex += " & ".join(["\\textbf{" + str(c) + "}" for c in df.columns]) + "\\\\\\hline \n"
    for index, row in df.iterrows():
        latex += " & ".join([f" {v} " for v in row]) + " \\\\ \n"
    latex += "\\end{tabularx}"
    print(latex)

In [ ]:
def woodelf_any_order_pdiv(model, data, global_importance=False, GPU=False):
    return woodelf.calculate_background_metric(
        model, consumer_data=data, background_data=data, metric=PDIV(), global_importance=global_importance, GPU=GPU
    )

def get_woodelf_pdp_testing_params():
    return [
        ("Exact PDP k=5",                  woodelf_pdp, dict(k = 5,         accurate = True,  centered = False, GPU = False)),
        ("Exact PDP k=10",                 woodelf_pdp, dict(k = 5,         accurate = True,  centered = False, GPU = False)),
        ("Exact PDP k=100",                woodelf_pdp, dict(k = 100,       accurate = True,  centered = False, GPU = False)),
        ("Exact full PDP",                 woodelf_pdp, dict(full_pdp=True, accurate = True,  centered = False, GPU = False)),
        ("Exact Joint PDP k=5",      woodelf_pdp_joint, dict(k = 5,         accurate = True,  centered = False, GPU = False)),
        ("Estimated PDP k=5",              woodelf_pdp, dict(k = 5,         accurate = True,  centered = False, GPU = False)),
        ("Estimated Joint PDP k=5",  woodelf_pdp_joint, dict(k = 5,         accurate = False, centered = False, GPU = False)),
        ("Any-Order PDIVs",     woodelf_any_order_pdiv, dict(global_importance = False,                         GPU = False)),
    ]

def messure_woodelf_pdp_times(model, data, params):
    running_results = {}
    for name, woodelf_func, running_params in params:
        print(name + ":")
        start_time = time.time()
        woodelf_func(model, data, **running_params)
        running_results[name] = round(time.time() - start_time, 2)
        print()
    return running_results

def messure_pdp_times_for_many_datasets(models, train_sets, params, alg_name='Woodelf CPU'):
    info = {'Dataset': [], 'Task': [], alg_name: []}
    for name, model in models.items():
        running_results = messure_woodelf_pdp_times(model, train_sets[name], params)
        info['Dataset'].extend([name] * len(running_results))
        info['Task'].extend(list(running_results.keys()))
        info[alg_name].extend(list(running_results.values()))
    return pd.DataFrame(info)

In [ ]:
running_times_df = messure_pdp_times_for_many_datasets(models, trains, get_woodelf_pdp_testing_params())

Exact PDP k=5:
Building the points took: 0.00672602653503418 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 408.98it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 941.93it/s]

Exact PDP k=10:
Building the points took: 0.004907131195068359 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 459.17it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 980.17it/s]

Exact PDP k=100:
Building the points took: 0.0032501220703125 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 406.41it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 841.96it/s]

Exact full PDP:
Building the points took: 0.0322413444519043 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 394.20it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 840.09it/s]

Exact Joint PDP k=5:
Building the points took: 0.005749225616455078 sec. The size of the created df 100

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 198.84it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 598.83it/s]

Estimated PDP k=5:
Building the points took: 0.004324913024902344 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 425.21it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 804.68it/s]

Estimated Joint PDP k=5:
Building the points took: 0.004570484161376953 sec. The size of the created df 100

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 289.83it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 771.87it/s]

Any-Order PDIVs:

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 145.96it/s]

cache misses: 124, cache used: 1026

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 482.38it/s]

Exact PDP k=5:
Building the points took: 0.009853601455688477 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 437.97it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 822.49it/s]

Exact PDP k=10:
Building the points took: 0.008553743362426758 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 447.78it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 815.92it/s]

Exact PDP k=100:
Building the points took: 0.01492452621459961 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 405.65it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 782.79it/s]

Exact full PDP:
Building the points took: 0.028239727020263672 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 439.93it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 637.82it/s]

Exact Joint PDP k=5:
Building the points took: 0.014595746994018555 sec. The size of the created df 125

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 233.16it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 504.40it/s]

Estimated PDP k=5:
Building the points took: 0.011809825897216797 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 396.75it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 678.20it/s]

Estimated Joint PDP k=5:
Building the points took: 0.01623988151550293 sec. The size of the created df 125

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 376.89it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 613.13it/s]

Any-Order PDIVs:

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 106.06it/s]

cache misses: 63, cache used: 1111

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 299.46it/s]

Exact PDP k=5:
Building the points took: 0.011216878890991211 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:01<00:00, 97.54it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 198.47it/s]

Exact PDP k=10:
Building the points took: 0.007614612579345703 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:01<00:00, 93.74it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 186.28it/s]

Exact PDP k=100:
Building the points took: 0.006461381912231445 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 105.89it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 177.49it/s]

Exact full PDP:
Building the points took: 0.07163405418395996 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:01<00:00, 96.23it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 157.48it/s]

Exact Joint PDP k=5:
Building the points took: 0.010501384735107422 sec. The size of the created df 75

Preprocessing the trees: 100%|██████████| 100/100 [00:01<00:00, 51.50it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 107.28it/s]

Estimated PDP k=5:
Building the points took: 0.007326841354370117 sec

Preprocessing the trees: 100%|██████████| 100/100 [00:01<00:00, 98.04it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 177.74it/s]

Estimated Joint PDP k=5:
Building the points took: 0.010833978652954102 sec. The size of the created df 75

Preprocessing the trees: 100%|██████████| 100/100 [00:00<00:00, 101.05it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:00<00:00, 150.14it/s]

Any-Order PDIVs:

Preprocessing the trees: 100%|██████████| 100/100 [00:02<00:00, 37.15it/s]

cache misses: 203, cache used: 4287

Computing the values: 100%|██████████| 100/100 [00:03<00:00, 28.00it/s]

In [ ]:
def sota_pdp(model, data, k: int = 5, accurate: bool = True):
    failed_columns = []
    method = 'brute' if accurate else 'recursion'
    # We have to run this one feature at a time, trying to provide significant more than 1 (say 16 features at a time) crashes the RAM :(
    for f in tqdm(data.columns):
        try:
            accurate_pdp_result_sklean = sklearn.inspection.partial_dependence(
                estimator=model, X=data, features=[f], feature_names=[f], grid_resolution=k, method=method, kind='average'
            )
        except ValueError:
            print(f"{f} has failed...")

    print()
    print(f"{len(failed_columns)} failed columns: {failed_columns}")

def sota_full_pdp(model, data, accurate: bool = True):
    points_for_full_pdp = build_points_for_full_pdp(data=data, model=model, as_df=False)
    failed_columns = []
    method = 'brute' if accurate else 'recursion'
    for f in tqdm(data.columns):
        try:
            if len(points_for_full_pdp[f]) > 0:
                accurate_pdp_result_sklean = sklearn.inspection.partial_dependence(
                    estimator=model, X=data, features=[f], feature_names=[f], custom_values={f: points_for_full_pdp[f]}, method=method, kind='average'
                )
        except ValueError:
            failed_columns.append(f)

    print()
    print(f"{len(failed_columns)} failed columns are: {failed_columns}")

def sota_joint_pdp(model, data, k: int = 5, accurate: bool = True):
    features = data.columns
    failures = 0
    successes = 0
    method = 'brute' if accurate else 'recursion'
    for i1 in tqdm(range(len(features))):
        for i2 in range(i1 + 1, len(features)):
            try:
                accurate_pdp_result_sklean = sklearn.inspection.partial_dependence(
                    estimator=model, X=data, features=[(i1,i2)], grid_resolution=k, method=method, kind='average'
                )
                successes += 1
            except ValueError:
                failures += 1

    print()
    print(f"Had {failures} failures and {successes} successful computations")

In [ ]:
def get_sota_pdp_testing_params():
    return [
        ("Exact PDP k=5",                  sota_pdp, dict(k = 5,         accurate = True)),
        ("Exact PDP k=10",                 sota_pdp, dict(k = 10,        accurate = True)),
        ("Exact PDP k=100",                sota_pdp, dict(k = 100,       accurate = True)),
        ("Exact full PDP",            sota_full_pdp, dict(               accurate = True)),
        ("Exact Joint PDP k=5",      sota_joint_pdp, dict(k = 5,         accurate = True)),
        ("Estimated PDP k=5",              sota_pdp, dict(k = 5,         accurate = False)),
        ("Estimated Joint PDP k=5",  sota_joint_pdp, dict(k = 5,         accurate = False)),
    ]

In [ ]:
sota_times_df = messure_pdp_times_for_many_datasets(models, trains, get_sota_pdp_testing_params(), alg_name='SOTA')
sota_times_df

Exact PDP k=5:

100%|██████████| 10/10 [00:00<00:00, 40.96it/s]

0 failed columns: []

Exact PDP k=10:

100%|██████████| 10/10 [00:00<00:00, 25.50it/s]

0 failed columns: []

Exact PDP k=100:

100%|██████████| 10/10 [00:02<00:00,  3.67it/s]

0 failed columns: []

Exact full PDP:

100%|██████████| 10/10 [00:01<00:00,  8.13it/s]

0 failed columns are: []

Exact Joint PDP k=5:

100%|██████████| 10/10 [00:03<00:00,  2.84it/s]

Had 0 failures and 45 successful computations

Estimated PDP k=5:

100%|██████████| 10/10 [00:00<00:00, 647.60it/s]

0 failed columns: []

Estimated Joint PDP k=5:

100%|██████████| 10/10 [00:00<00:00, 107.90it/s]

Had 0 failures and 45 successful computations

Exact PDP k=5:

100%|██████████| 30/30 [00:00<00:00, 44.92it/s]

0 failed columns: []

Exact PDP k=10:

100%|██████████| 30/30 [00:01<00:00, 22.45it/s]

0 failed columns: []

Exact PDP k=100:

100%|██████████| 30/30 [00:12<00:00,  2.46it/s]

0 failed columns: []

Exact full PDP:

100%|██████████| 30/30 [00:03<00:00,  9.92it/s]

0 failed columns are: []

Exact Joint PDP k=5:

100%|██████████| 30/30 [00:46<00:00,  1.53s/it]

Had 0 failures and 435 successful computations

Estimated PDP k=5:

100%|██████████| 30/30 [00:00<00:00, 618.37it/s]

0 failed columns: []

Estimated Joint PDP k=5:

100%|██████████| 30/30 [00:01<00:00, 28.77it/s]

Had 0 failures and 435 successful computations

Exact PDP k=5:

100%|██████████| 8/8 [00:02<00:00,  3.49it/s]

0 failed columns: []

Exact PDP k=10:

100%|██████████| 8/8 [00:04<00:00,  1.93it/s]

0 failed columns: []

Exact PDP k=100:

100%|██████████| 8/8 [00:38<00:00,  4.83s/it]

0 failed columns: []

Exact full PDP:

100%|██████████| 8/8 [01:02<00:00,  7.87s/it]

0 failed columns are: []

Exact Joint PDP k=5:

100%|██████████| 8/8 [00:36<00:00,  4.60s/it]

Had 0 failures and 28 successful computations

Estimated PDP k=5:

100%|██████████| 8/8 [00:00<00:00, 323.75it/s]

0 failed columns: []

Estimated Joint PDP k=5:

100%|██████████| 8/8 [00:00<00:00, 68.24it/s]

Had 0 failures and 28 successful computations

               Dataset                     Task   SOTA
0             diabetes            Exact PDP k=5   0.25
1             diabetes           Exact PDP k=10   0.40
2             diabetes          Exact PDP k=100   2.73
3             diabetes           Exact full PDP   1.26
4             diabetes      Exact Joint PDP k=5   3.53
5             diabetes        Estimated PDP k=5   0.02
6             diabetes  Estimated Joint PDP k=5   0.10
7               cancer            Exact PDP k=5   0.67
8               cancer           Exact PDP k=10   1.34
9               cancer          Exact PDP k=100  12.19
10              cancer           Exact full PDP   3.06
11              cancer      Exact Joint PDP k=5  46.03
12              cancer        Estimated PDP k=5   0.05
13              cancer  Estimated Joint PDP k=5   1.05
14  california_housing            Exact PDP k=5   2.29
15  california_housing           Exact PDP k=10   4.14
16  california_housing          Exact PDP k=100  38.63
17  california_housing           Exact full PDP  63.07
18  california_housing      Exact Joint PDP k=5  36.84
19  california_housing        Estimated PDP k=5   0.03
20  california_housing  Estimated Joint PDP k=5   0.12

In [ ]:
def estimate_sota_pdiv_runtime(model, data):
    loaded_model = woodelf.load_decision_tree_ensamble_model(model, list(data.columns))
    total_exponential_time = 0
    n_features_lst = []
    for tree in loaded_model:
        tree_features = [n.feature_name for n in tree.bfs(including_leaves=False)]
        # print(len(tree_features))
        n_features = len(set(tree_features))
        n_features_lst.append(n_features)
        total_exponential_time += 2 ** n_features
    total_exponential_time

    c = 8.66579161428677e-08

    return (c * total_exponential_time * len(data))

pdivs_times = {}
for name, model in models.items():
    pdivs_times[name] = estimate_sota_pdiv_runtime(model, trains[name])
    print(f"{name} Any-Order PDIVs etsimated time: {pdivs_times[name]}")

diabetes Any-Order PDIVs etsimated time: 0.30394466834282335
cancer Any-Order PDIVs etsimated time: 4.3416447903571695
california_housing Any-Order PDIVs etsimated time: 34.982533461510016

In [ ]:
running_times_df["SOTA"] = (
    list(sota_times_df['SOTA'])[0:7] + [round(pdivs_times['diabetes'], 2)] +
    list(sota_times_df['SOTA'])[7:14] + [round(pdivs_times['cancer'], 2)] +
    list(sota_times_df['SOTA'])[14:] + [round(pdivs_times['california_housing'], 2)]
)

In [ ]:
running_times_df

               Dataset                     Task  Woodelf CPU   SOTA
0             diabetes            Exact PDP k=5         0.39   0.25
1             diabetes           Exact PDP k=10         0.36   0.40
2             diabetes          Exact PDP k=100         0.40   2.73
3             diabetes           Exact full PDP         0.44   1.26
4             diabetes      Exact Joint PDP k=5         0.72   3.53
5             diabetes        Estimated PDP k=5         0.40   0.02
6             diabetes  Estimated Joint PDP k=5         0.52   0.10
7             diabetes          Any-Order PDIVs         0.92   0.30
8               cancer            Exact PDP k=5         0.40   0.67
9               cancer           Exact PDP k=10         0.39   1.34
10              cancer          Exact PDP k=100         0.42  12.19
11              cancer           Exact full PDP         0.45   3.06
12              cancer      Exact Joint PDP k=5         0.70  46.03
13              cancer        Estimated PDP k=5         0.45   0.05
14              cancer  Estimated Joint PDP k=5         0.49   1.05
15              cancer          Any-Order PDIVs         1.32   4.34
16  california_housing            Exact PDP k=5         1.70   2.29
17  california_housing           Exact PDP k=10         1.74   4.14
18  california_housing          Exact PDP k=100         1.64  38.63
19  california_housing           Exact full PDP         1.90  63.07
20  california_housing      Exact Joint PDP k=5         3.03  36.84
21  california_housing        Estimated PDP k=5         1.72   0.03
22  california_housing  Estimated Joint PDP k=5         1.81   0.12
23  california_housing          Any-Order PDIVs         6.35  34.98

In [ ]:
df_to_latex(running_times_df[["Dataset", "Task", "SOTA", "Woodelf CPU"]])

\begin{tabularx}{\columnwidth}{r|r|r|r}
\textbf{Dataset} & \textbf{Task} & \textbf{SOTA} & \textbf{Woodelf CPU}\\\hline
 diabetes  &  Exact PDP k=5  &  0.25  &  0.39  \\
 diabetes  &  Exact PDP k=10  &  0.4  &  0.36  \\
 diabetes  &  Exact PDP k=100  &  2.73  &  0.4  \\
 diabetes  &  Exact full PDP  &  1.26  &  0.44  \\
 diabetes  &  Exact Joint PDP k=5  &  3.53  &  0.72  \\
 diabetes  &  Estimated PDP k=5  &  0.02  &  0.4  \\
 diabetes  &  Estimated Joint PDP k=5  &  0.1  &  0.52  \\
 diabetes  &  Any-Order PDIVs  &  0.3  &  0.92  \\
 cancer  &  Exact PDP k=5  &  0.67  &  0.4  \\
 cancer  &  Exact PDP k=10  &  1.34  &  0.39  \\
 cancer  &  Exact PDP k=100  &  12.19  &  0.42  \\
 cancer  &  Exact full PDP  &  3.06  &  0.45  \\
 cancer  &  Exact Joint PDP k=5  &  46.03  &  0.7  \\
 cancer  &  Estimated PDP k=5  &  0.05  &  0.45  \\
 cancer  &  Estimated Joint PDP k=5  &  1.05  &  0.49  \\
 cancer  &  Any-Order PDIVs  &  4.34  &  1.32  \\
 california_housing  &  Exact PDP k=5  &  2.29  &  1.7  \\
 california_housing  &  Exact PDP k=10  &  4.14  &  1.74  \\
 california_housing  &  Exact PDP k=100  &  38.63  &  1.64  \\
 california_housing  &  Exact full PDP  &  63.07  &  1.9  \\
 california_housing  &  Exact Joint PDP k=5  &  36.84  &  3.03  \\
 california_housing  &  Estimated PDP k=5  &  0.03  &  1.72  \\
 california_housing  &  Estimated Joint PDP k=5  &  0.12  &  1.81  \\
 california_housing  &  Any-Order PDIVs  &  34.98  &  6.35  \\
\end{tabularx}